name: 'Tag validator and retag'
description: 'This action will check if the tag is rc and create a new tag for release'
inputs:
  ORIGINAL_TAG:  # id of input
    description: 'Original tag'
    required: true
    default: ${{ github.ref_name }}
  SUB_STRING: 
    description: 'Sub string for rc tag'
    required: true
    default: "-rc"
outputs:
  NEW_TAG:
    description: "The new tag for release"
    value: ${{ steps.retag.outputs.NEW_TAG }}
runs:
  using: "composite"
  steps:
    - name: validate tag
      run: |
        if [[ -z "${{ inputs.ORIGINAL_TAG }}" ]]; then
          echo "The value of ORIGINAL_TAG is ${{ inputs.ORIGINAL_TAG }}"
          echo "Setting the value of ORIGINAL_TAG to ${{ github.ref_name }}"
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

        elif [[ ! -z "${{ inputs.ORIGINAL_TAG }}" ]]; then
          echo "ORIGINAL_TAG isn't null, assigning TAG to ${{ inputs.ORIGINAL_TAG }}"
          echo "TAG=${{ inputs.ORIGINAL_TAG }}" >> $GITHUB_ENV

        fi
        
      shell: bash

    - name: release candidate tag validation
      run: |
        if [[ "${{ env.TAG }}" == *"${{ inputs.SUB_STRING }}"* ]]; then
            echo "Release candidate tag found."
        else
            echo "Release candidate tag not found."
            exit 1
        fi
      shell: bash


    - id: retag
      name: export tag
      run: | 
          NEW_TAG=
          echo "Original tag: ${{ env.TAG }}"
          NEW_TAG=$(echo ${{ env.TAG }} | awk -F '-rc' '{print $1}')
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
      shell: bash