name: Coverage-Check

on:
  workflow_call:
    inputs:
      COVERAGE-LIMIT: 
        required: true
        type: string

jobs: 
  test-coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    needs: [test_pr_checks]
    steps:
      - name: Get Coverage Data from Coveralls by commit SHA
        id: coveralls
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.COVERALLS_TOKEN }}" \
                          "https://coveralls.io/builds/${{ github.sha }}.json")
          current-coverage=$(echo $response | jq '.covered_percent')
          echo "CURRENT-COVERAGE=$current-coverage" >> $GITHUB_ENV
      
      - name: Use Coverage Data
        run: |  
          echo "Current Coverage is: $CURRENT-COVERAGE"

      - name : test coverage
        with:
          coverage-limit: ${{ inputs.COVERAGE-LIMIT }}
        run: |    
          if (( $(echo "$CURRENT-COVERAGE < $coverage-limit" |bc -l) )); then
            echo "Code coverage is less than $coverage-limit%, blocking the PR"
            exit 1
          fi