name: Kubescape scanning for misconfigurations

on:
  workflow_call:
    inputs:
      FAILEDTHRESHOLD:
        required: true
        type: number

jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results
        account: ${{secrets.KUBESCAPE_ACCOUNT}}
        # files: "examples/*.yaml"
        # frameworks: |
        #   nsa,mitre
#         failedThreshold: ${{ inputs.FAILEDTHRESHOLD }}
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
