name: Release
on:
  workflow_call:
    inputs:
      GO_VERSION:
        required: true
        type: string
      GO111MODULE:
        required: false
        type: string
      CGO_ENABLED:
        required: false
        type: number
        default: 1
      RELEASE:
        required: true
        type: string
      IS_DRAFT:
        required: false
        type: boolean
        default: false
      BUILD_PATH:
        required: false
        type: string
        default: "./..."
      UNIT_TESTS_PATH:
        required: false
        type: string
        default: "./..."
      # TEST_MULTI_ENVIRONMENTS:
      #   required: false
      #   type: boolean
      #   default: true
  # push:
  #   tags:
  #     - 'v*.*.*-rc.*'

jobs:
  test:
    uses: ./.github/workflows/go-basic-tests.yaml
    with:
      GO_VERSION: ${{ inputs.GO_VERSION }}
      GO111MODULE: ${{ inputs.GO111MODULE }}
      CGO_ENABLED: ${{ inputs.CGO_ENABLED }}
      UNIT_TESTS_PATH: ${{ inputs.UNIT_TESTS_PATH }}
      BUILD_PATH: ${{ inputs.BUILD_PATH }}
      # TEST_MULTI_ENVIRONMENTS: ${{ inputs.TEST_MULTI_ENVIRONMENTS }}
    secrets: inherit

  release:
    needs: test
    # outputs:
    #   NEW_TAG: ${{ steps.tag-calculator.outputs.NEW_TAG }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      # - id: tag-calculator
      #   uses: kubescape/workflows/.github/actions/tag-action@main
      #   with: 
      #     ORIGINAL_TAG: ${{ inputs.TAG }}
      #     SUB_STRING: "-rc"
      - uses: actions/checkout@v3
      - name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false