name: pr-checks

on:
  pull_request:
    types: [ edited, opened, synchronize, reopened ]
    paths-ignore:
      - '**.md' ### Ignore running when .md files change

jobs:
  validate-go-basic-tests-file:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/go-basic-tests.yaml
    with:
      GO_VERSION: 1.19
    secrets: inherit

  validate-package-releaser-file:
    needs: validate-go-basic-tests-file
    permissions:
      pull-requests: write
    uses: ./.github/workflows/package-release.yaml
    with:
      RELEASE: "v0.0.${{ github.run_number }}"
      GO_VERSION: 1.19
      IS_DRAFT: true
    secrets: inherit

  # TODO: Remove created tag
 