name: reran-test-untill-fix

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["system-sanity-check"]
    types:
      - completed
    schedule:
    - cron: "*/4 * * * *"

jobs:
  ks-and-repo-test:
    name: ks-and-repo-test-reran
    steps:
      - run: echo "reran the test"