name: reran-test-untill-fix

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["sanity-check-for-BE"]
    types:
      - completed
    schedule:
    - cron: "*/4 * * * *"

jobs:
  ks-and-repo-test:
    name: ks-and-repo-test
    uses: ./.github/workflows/sanity-check.yaml # @sanity_check
    with:
      BINARY_TESTS: '[ 
                        "scan_nsa"
                      ]'
    secrets: inherit