name: reran-test-untill-fix
on:
  workflow_run:
    workflows: ["sanity-check-for-BE"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "sanity-check-for-BE failed!"
