name: sanity-check-for-BE

  # Controls when the workflow will run
on:
  workflow_dispatch:
  # # Triggers the workflow every 30 minutes
  # schedule:
  # - cron: "*/30 * * * *"
env:
  FIX_FLOW: false
  
  push:
    branches:
    - sanity_check

jobs:
  ks-and-repo-test:
    name: ks-and-repo-test
    uses: ./.github/workflows/sanity-check.yaml # @sanity_check
    with:
      BINARY_TESTS: '[ 
                        "scan_nsa-a"
                      ]'
    secrets: inherit

  set-env:
    needs: [ks-and-repo-test]
    if: failure()
    env:
      FIX_FLOW: true
    steps:
      - run: echo ${{env.FIX_FLOW}}
    

  better-up-time:
    needs: [ks-and-repo-test]
    name: better-up-time
    runs-on: ubuntu-latest
    if: failure()
    #if: ${{ contains(needs.*.result, 'failure') }}
    steps:
      - run: echo "test failed"
      # - run: |
      #     curl --request POST \
      #       --url https://betteruptime.com/api/v2/incidents \
      #       --header "Authorization: Bearer ${{ secrets.BETTER_UPTIME_TOKEN }}" \
      #       --header 'Content-Type: application/json' \
      #       --data '{"summary": "Test incident","sms": "false", "email": "true", "call": "true", "requester_email": "borisv@armosec.io", "description": "Automatic sanity check failed ! "}'

  call-reran:
    needs: [ks-and-repo-test]
    if: failure()
    name: ks-and-repo-test
    uses: ./.github/workflows/reran-test-until-fix.yaml
    secrets: inherit