name: sanity-check-for-BE

  # Controls when the workflow will run
on:
  workflow_dispatch:
  # # Triggers the workflow every 30 minutes
  # schedule:
  # - cron: "*/30 * * * *"
  push:
    branches:
    - sanity_check

concurrency:
  group: sanity
  cancel-in-progress: false

jobs:
  ks-and-repo-test:
    name: ks-and-repo-test
    uses: ./.github/workflows/sanity-check.yaml # @sanity_check
    with:
      IF_FAILED: false
      BINARY_TESTS: '[ 
                        "scan_nsa-a"
                      ]'
    secrets: inherit

    name: retry-if-fail
    uses: nick-fields/retry@v2
    with:
      timeout_seconds: 15
      max_attempts: 2
      retry_on: error
      IF_FAILED: false
      BINARY_TESTS: '[ 
                        "scan_nsa-a"
                      ]'
    secrets: inherit

    

  better-up-time:
    needs: [ks-and-repo-test]
    name: better-up-time
    runs-on: ubuntu-latest
    if: failure()
    #if: ${{ contains(needs.*.result, 'failure') }}
    steps:
      - run: echo "test failed"
      # - run: |
      #     curl --request POST \
      #       --url https://betteruptime.com/api/v2/incidents \
      #       --header "Authorization: Bearer ${{ secrets.BETTER_UPTIME_TOKEN }}" \
      #       --header 'Content-Type: application/json' \
      #       --data '{"summary": "Test incident","sms": "false", "email": "true", "call": "true", "requester_email": "borisv@armosec.io", "description": "Automatic sanity check failed ! "}'

  call-reran:
    needs: [ks-and-repo-test]
    if: failure()
    name: repeated-test
    uses: ./.github/workflows/sanity-check.yaml # @sanity_check
    with:
      IF_FAILED: true
      BINARY_TESTS: '[ 
                        "scan_nsa"
                      ]'
    secrets: inherit